# Generated by Django 5.0 on 2024-02-23 03:15

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bangla', 'bangla'), ('English', 'English'), ('Urdu', 'Urdu'), ('Hindi', 'Hindi'), ('Arabic', 'Arabic')], default='bangla', max_length=100),
        ),
    ]
