# Generated by Django 5.0 on 2024-02-23 03:16

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0004_post_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Urdu', 'Urdu'), ('Hindi', 'Hindi'), ('Arabic', 'Arabic')], default='Bangla', max_length=100),
        ),
    ]
