# Generated by Django 5.0 on 2024-02-23 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0005_alter_post_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='medium',
        ),
    ]
